#
#  ArcaneColors - A new age of chatcolor plugins.
#             Created by Jayie
#


# Placeholders. (Format) Placeholder | Description.
# %player% | Always returns the commandsender.
# %color% | Returns the color chosen (in color format)
# %color-name% | Returns the color chosen (in string format)
# %target% | Returns the target name (only for staff commands)
# %prefix% | Returns the prefix of the plugin.
# %status% | Returns the status of a toggle.

# Supports HEX Colours on ALL messages.
# Add my discord for support @ Jayie#0666

Plugin:
  Prefix: '&8[&9AC&8]'
  Database:
    # Options: MySQL, H2. Recommended MySQL.
    Type: 'H2'
    # Ignore this part if you have chosen H2.
    MySQL:
      Address: 'localhost'
      Port: '3306'
      Username: 'root'
      Password: 'error404'
      Database: 'ac_colors'
  Permissions:
    Color:
      # All colors.
      Set: 'arcanecolors.color.set'
      Hex: 'arcanecolors.color.hex'
      Force: 'arcanecolors.color.force'
      CertainColor: 'arcanecolors.color.%color-name%'
    Reset:
      Player: 'arcanecolors.reset'
      Force: 'arcanecolors.reset.force'
    Special:
      Bold: 'arcanecolors.bold'
      Italic: 'arcanecolors.italic'
      Underline: 'arcanecolors.underline'
      Magic: 'arcanecolors.magic'
      Strikethrough: 'arcanecolors.strikethrough'
    Admin:
      Reload: 'arcanecolors.reload'
      AllPerms: 'arcanecolors.*'


GUI:
  Settings:
    Title: '&cChatColor GUI'
    OpeningMessage: '&aOpening the chatcolor gui...'
    Items:
      Filler: 'WHITE_STAINED_GLASS_PANE'
      Colors:
        # Options: Wool, Concrete, Dye. Changes the blocks that the colors are showed as.
        Type: 'Dye'
        # Options: Ascending, Descending, Random. Changes the order of the colors in the GUI.
        Order: 'Ascending'


#
Messages:
  Color:
    Success: '%prefix% &7You have chosen %color%THIS as your chatcolor.'
    ForceSet:
      Staff: '%prefix% &7You have set %color%THIS &7as the chatcolor for &e%target%'
      Player: '%prefix% &7Your color was set to %color%THIS &7by &e%player%'
  Reset:
    Success: '%prefix% &7You have reset your chatcolor.'
    ForceReset:
      Staff: '%prefix% &7You reset chatcolor for &e%target%'
      Player: '%prefix% &7Your color was reset by &e%player%'
  Bold:
    Success: '%prefix% &7You have set &eBOLD &7%status%.'
  Italic:
    Success: '%prefix% &7You have set &eITALIC &7%status%.'
  Magic:
    Success: '%prefix% &7You have set &eMAGIC &7%status%.'
  Underline:
    Success: '%prefix% &7You have set &eUNDERLINE &7%status%.'
  Strikethrough:
    Success: '%prefix% &7You have set &eStrikethrough &7%status%.'



# Error messages.
Errors:
  NoPermissions: '%prefix% &cError: You do not have permission to %permission%.'
  InvalidArgument: '%prefix% &cError: Invalid Argument. Try /color help.'
  NullPlayer: '%prefix% &cError: That player does not exist or is not online.'