#
#
#  ArcaneColors - A new age of chatcolor plugins.
#             Created by Jayie
#
#
# (!) ALL FEATURES AND MESSAGES SUPPORT HEX COLOURS. (!)
# (!) HEX FORMAT &#(6 digit code) e.g. &#ffffff (!)
#
# To set a groups default color add them the permission.
# arcanecolors.defaults.(color) <- only works with default minecraft colours.

# Placeholders. (Format) Placeholder | Description.
# %player% | Always returns the commandsender.
# %color% | Returns the color chosen (in color format)
# %color-name% | Returns the color chosen (in string format)
# %target% | Returns the target name (only for staff commands)
# %status% | Returns the status of a toggle.
#
# Join my discord for support @ https://discord.gg/cCPpfaJAtM
#

# Plugin settings.
Plugin:
  # Put infront of all messages.
  Prefix: '&8[&9AC&8]'
  Database:
    MySQL:
      Address: 'localhost'
      Port: '3306'
      Username: 'root'
      Password: 'error404'
      Database: 'ac_colors'
  Permissions:
    Color:
      # Access to all colors.
      Set: 'arcanecolors.color.set'
      Hex: 'arcanecolors.color.hex'
      Force: 'arcanecolors.color.force'
      # Access to certain colors.
      CertainColor: 'arcanecolors.color.%color-name%'
    Reset:
      Player: 'arcanecolors.reset'
      Force: 'arcanecolors.reset.force'
    Special:
      Bold: 'arcanecolors.bold'
      Italic: 'arcanecolors.italic'
      Underline: 'arcanecolors.underline'
      Magic: 'arcanecolors.magic'
      Strikethrough: 'arcanecolors.strikethrough'
    Admin:
      Reload: 'arcanecolors.reload'
      AllPerms: 'arcanecolors.*'
  DefaultColor: '&7'


# GUI settings, shown on command /color gui.
GUI:
  Settings:
    Title: '&cChatColor GUI'
    OpeningMessage: '%prefix% &aOpening the chatcolor gui...'
    Items:
      Filler: 'WHITE_STAINED_GLASS_PANE'
      Colors:
        # Options: Wool, Concrete, Dye. Changes the blocks that the colors are showed as.
        Title: ''
        Type: 'Dye'
      Staff:
        Title: ''
      Special:
        Title: ''


# All plugin messages.
Messages:
  Color:
    Success: '&7You have chosen %color%THIS as your chatcolor.'
    ForceSet:
      Staff: '&7You have set %color%THIS &7as the chatcolor for &e%target%'
      Player: '&7Your color was set to %color%THIS &7by &e%player%'
  Reset:
    Success: '&7You have reset your chatcolor.'
    ForceReset:
      Staff: '&7You reset chatcolor for &e%target%'
      Player: '&7Your color was reset by &e%player%'
  Bold:
    Success: '&7You have set &eBOLD &7%status%.'
  Italic:
    Success: '&7You have set &eITALIC &7%status%.'
  Magic:
    Success: '&7You have set &eMAGIC &7%status%.'
  Underline:
    Success: '&7You have set &eUNDERLINE &7%status%.'
  Strikethrough:
    Success: '&7You have set &eStrikethrough &7%status%.'



# Error messages.
Errors:
  NoPermissions: '&cError: You do not have permission to that.'
  InvalidArgument: '&cError: Invalid Argument. Try /color help.'
  NullPlayer: '&cError: That player does not exist or is not online.'
