name: ArcaneColors
version: '${project.version}'
main: me.jayie.arcanecolors.ArcaneColors
api-version: 1.18
authors: [ Jayie ]
description: ChatColor plugin made for ArcaneMC
commands:
  chatcolor:
    aliases: [cc, color]
    description: Base player commands for ArcaneColors.